### ISSUE TITLE
Quick links box

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/genizah-mss#1]
I've had a go at implementing Cesar's main request when I visited him, which was to have something to show at a glance what a manuscript contains, and be able to jump down to the bit you are interested in. It ignores the hierarchy of `msPart` and nested `msItem` elements, flattening it into a list of works/fragments.

It is now on the Genizah QA site, for example this is quite a complicated one:

http://genizah-qa.bodleian.ox.ac.uk/catalog/volume_98

I haven't set it up on the Hebrew QA site, so you can see the difference here:

http://hebrew-qa.bodleian.ox.ac.uk/catalog/volume_98

Here's a much simpler manuscript, where it is a lot less useful:

http://genizah-qa.bodleian.ox.ac.uk/catalog/volume_6

@IgnatG, @ahankinson: Before I take this back to Cesar, is this workable? I've used inline style attributes just to prove the concept, but it'd obviously need doing properly, with a solution for mobile browsers and when printing (maybe just hide it?) Possibly a Wikipedia-style contents box that appears in the main block of text and has a hide/show button would be better, but that'd require JavaScript.

Something like this will likely be needed for Fihrist, and possibly some of the other TEI catalogues.

**Comment by andrew-morrison** [comment]
Note, Genizah's folio numbering is quite simple. In other catalogues they might be more like: 

> fol. 177v-184r

**Comment by andrew-morrison** [comment]
Your changes are up on the QA sites, e.g.:

http://hebrew-qa.bodleian.ox.ac.uk/catalog/manuscript_57
http://genizah-qa.bodleian.ox.ac.uk/catalog/volume_75

As discussed:

- Reinstate #anchor in URLs (so it doesn't break the back button)
- Prevent div of class "footer" (catalogue images on Genizah only) from being included in the navigation

Some other ideas:

- Hide the navigation completely when printing?
- Hide or modify it on mobiles?

**Comment by andrew-morrison** [comment]
Also maybe make the lines between each row in the navigation the same light grey (#eaeaea) as the lines in the main body of the content?

**Comment by IgnatG** [comment]
done

**Comment by andrew-morrison** [comment]
I've redeployed to QA and the back button is still impaired. In Firefox and Chrome:

1. The first time you click on a link jumps to the right point, with the #anchor on the end of the URL,
2. Clicking back does return to the top and no #anchor
3. But then the page reloads, and takes you back down again.
4. If you then scroll back up, and click on another link in the nav, and then click back, it does nothing except remove the box around the div. It doesn't return you to the top.

Also the lines between rows in the nav are light grey on genizah-qa but dark drey on hebrew-qa.

**Comment by IgnatG** [comment]
I've removed the JS code from both of them. Give it a go now.

**Comment by andrew-morrison** [comment]
OK, redeployed again, and the back button is working fine. Pity it means no box displayed around the work or part you jump to, that was nice, but the extra spacing added yesterday helps. I'll send Cesar an email asking him to take a look.
